### ISSUE TITLE
[Bug] /close error

### ISSUE THREAD

**Issue by Swift-ality** [WhyClove/admincraft-meta#6]
**Describe the bug**
I ran /close in a thread and it throwed errors

**To Reproduce**
1. run the command /close

**Expected behavior**
Shoud close

**Error logs**
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/ubuntu/admincraft/admincraft-meta/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/ubuntu/admincraft/admincraft-meta/node_modules/@discordjs/rest/dist/index.js:835:23)
    at async _REST.request (/home/ubuntu/admincraft/admincraft-meta/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async ChatInputCommandInteraction.reply (/home/ubuntu/admincraft/admincraft-meta/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:114:5)
    at async Object.execute (/home/ubuntu/admincraft/admincraft-meta/commands/close.js:90:17)

**Comment by WhyClove** [comment]
Thanks for reporting the error, it is very much appreciated, with [b04a4a5](https://github.com/WhyClove/admincraft-meta/commit/b04a4a5e33e0ae15fca02cf8208bf5416cf675a7) I was able to fix the issue.  Have a good day
